name: Manual PyInstaller Build

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    name: Manual PyInstaller Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtualenv
        run: python -m venv .venv

      - name: Activate virtualenv and install requirements
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          source .venv/bin/activate
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          source .venv/bin/activate
          pyinstaller --onefile main.py

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoDork-binary
          path: dist/main

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
           tag_name: "autodork-manual-build-${{ github.run_id }}"
           name: "Manual PyInstaller Build ${{ github.run_id }}"
           files: dist/main
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
