name: Media Organizer Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'media-organizer-v*'

jobs:
  release:
    name: Package and Release Media Organizer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check Python version
        run: python --version

      - name: Remove old zip if exists
        run: rm -f Media_Organizer.zip

      - name: Zip Media_Organizer folder
        run: |
          cd Media_Organizer
          zip -r ../Media_Organizer.zip . -x '*.git*'

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: Media_Organizer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
